// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtudfimxbmokjmncinuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dWRmaW14Ym1va2ptbmNpbnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODI0MzMsImV4cCI6MjA2MjM1ODQzM30.eVdjeTJdGm0_DHTWm5Jwh_6MSsOxlB2EGDJLLCsC-JQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);