// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubwrbituvkmlthvjosrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVid3JiaXR1dmttbHRodmpvc3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDE5MTEsImV4cCI6MjA2NjE3NzkxMX0.Vti85oqQJjWeZhVyg-TG-9qODQ3CWgLoqUUBtsDR_4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);